services:
  app:
    image: php:8.2-apache
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./src/docker/apache.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql &&
      a2enmod rewrite &&
      apache2-foreground"

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
